- host: Host_A
  user: almalinux
  key_filename: ~/.ssh/id_rsa
  buffer_lines: 5
  root_access_type: sudo
  log_files:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
  filters:
    - "ERROR"
    - "CRITICAL"
    - "404"

- host: Host_B
  user: pablo
  key_filename: ~/.ssh/id_rsa
  buffer_lines: 10
  root_access_type: sudo
  log_file: /var/log/syslog

- host: localhost
  is_localhost: true
  buffer_lines: 5
  root_access_type: sudo
  log_files:
    - /var/log/system.log

