- host: purplemanul.puffyclouds.xyz
  user: almalinux
  key_filename: /Users/pawelsuchanecki/.ssh/id_rsa
  log_file: /var/log/nginx/access.log-20230622
  delay: 5
  buffer_lines: 10

- host: refurby
  user: pablo
  key_filename: /Users/pawelsuchanecki/.ssh/id_rsa
  log_file: /var/log/syslog
  delay: 60
  buffer_lines: 5

