- host: purplemanul.puffyclouds.xyz
  user: almalinux
  key_filename: /Users/pawelsuchanecki/.ssh/id_rsa
  login_timeout: 5
  log_file: /var/log/nginx/access.log-20230622
  delay: 5
  buffer_lines: 10
  root_access_type: sudo

- host: refurby
  user: pablo
  key_filename: /Users/pawelsuchanecki/.ssh/id_rsa
  login_timeout: 3 
  log_file: /var/log/syslog
  delay: 60
  buffer_lines: 5
  root_access_type: sudo

- host: z18 
  user: pawel 
  key_filename: /Users/pawelsuchanecki/.ssh/id_rsa
  login_timeout: 8 
  log_file: /var/log/authlog
  delay: 60
  buffer_lines: 5
  root_access_type: doas


